# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.555309347708
    has_acceleration_limits: true
    max_acceleration: 9999
  joint_2:
    has_velocity_limits: true
    max_velocity: 4.031710572108
    has_acceleration_limits: true
    max_acceleration: 9999
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.235987755982
    has_acceleration_limits: true
    max_acceleration: 9999
  joint_4:
    has_velocity_limits: true
    max_velocity: 10.41961563438
    has_acceleration_limits: true
    max_acceleration: 9999
  joint_5:
    has_velocity_limits: true
    max_velocity: 11.15265392022
    has_acceleration_limits: true
    max_acceleration: 9999
  joint_6:
    has_velocity_limits: true
    max_velocity: 15.13200461478
    has_acceleration_limits: true
    max_acceleration: 9999